generate.py

This PR removes the repeating H2O logo from the background, and - hopefully - incorporates the H2O color theme to the app. I say hopefully, because I have not yet got a local dev environment running, lacking CUDA, and probably some other things necessary to successfully run `generate.py` - so I was not able to test this locally.
This is just a simple fix - but it might be good to start working more on a customized UI of some sort, if that is warranted at this point.
The UI should look something similar to this (though with slightly different colors for the yellows and grays):
Light mode:
Dark mode:

h2o theme for background

---

generate.py
utils.py

Now must be directory. File will be called history.json.

Use SAVE_DIR and --save_dir instead of SAVE_PATH and --save_path.

---

client_test.py
generate.py

And simplify client to just chat=False case since chat requires going through disk jsons and not useful/required for client calls.

Make chat optional from UI/client

---

generate.py
h2o_gradio_theme.py

This PR does the following for the Gradio app:
- Adds H2O logo to header
- Creates an H2O theme, using H2O brand colors
- Improves accessibility by adjusting colors for dark mode
- Tweaks a few things to make them line up better
- Eliminates the `h2ocolors` argument
If we need to retain the `h2ocolors` argument, please let me know, and I can add that back.
Revised UI looks like this:

H2O gradio theme

---

create_data.py
finetune.py

Refactor finetune so some of it can be used to check data and its tokenization

---

INSTALL.md
finetune.py
llama_flash_attn_monkey_patch.py
requirements.txt
tests/test_check_requirements.py
tests/test_requirements.py

Note:
Requires A100+ to work OOTB without patching transformers or using nightly torch to avoid errors.
Would need to patch transformers https://github.com/lm-sys/FastChat/issues/581#issuecomment-1522860263
We could also try bettertransformers wrapper, which wraps HF models into BT models, using native torch version of flash attention (they say slower but more memory efficient): 
https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html#:~:text=Scaled%20dot%20product%20attention%20attempts,for%20enabling%20and%20disabling%20implementations.
That might require pytorch nightly to fix a related bug where they should have disabled fast attention for some head sizes if don't have sm80.  But we can then at least test on A6000/4090.  But should then all work …

Llama flash attn

---

INSTALL-DOCKER.md
TRITON.md

For https://github.com/h2oai/h2ogpt/issues/87

Add Triton deployment template.

---

create_data.py

```
pytest -s -v tests/create_data.test_check_unhelpful
```
gives (for just bot responses) for `openassistant_oasst1_h2ogpt_graded.json`
```
{   'As a large language model': 15,
'As an artificial intelligence I do not have the capability': 2,
'I am not capable of': 15,
'I am sorry': 41,
"I didn't understand your question": 1,
"I'm sorry": 279,
"I'm sorry, I cannot perform this task as I am an AI language model and do not have access": 3,
"I'm sorry, but as an AI language model": 19,
'You need to provide more context': 3,
'as an AI language model': 50,
'do not have access': 20,
'nor am I capable': 1,
'provide more context': 26,
'sorry, but as an AI language model': 26}
total_bads_bots: 501
```
For `h2ogpt-oig-oasst1-instruct-cleaned-v2.json`:
```
{   'As a large language model': 25,
'As an …
```

Check data for unhelpful responses

---

README.md

This PR contains edits to the README file (typo fix and readability improvements).

[DOCS] README typo fix and readability improvements

---

finetune.py
generate.py

Follow: https://huggingface.co/OpenAssistant/oasst-sft-7-llama-30b-xor
and add prompt_type stuff.  bit hacky in dealing with special chars.

Support OpenAssistant models in basic form, including 30B xor one

---

FINETUNE.md
create_data.py
finetune.py

[wikitext.zip](https://github.com/h2oai/h2ogpt/files/11423008/wikitext.zip)

Improve data prep

---

README.md
README_LangChain.md
generate.py
gpt_langchain.py
gradio_runner.py
make_db.py
tests/test_langchain_units.py

```
=================================================================== 1 failed, 14 passed, 7 skipped, 1 xpassed, 9 warnings in 353.05s (0:05:53) ====================================================================
```

Allow CLI add to db and clean-up handling of evaluate args

---

generate.py
gradio_runner.py
tests/test_client_calls.py
tests/test_eval.py

```
=================================================================== 1 failed, 28 passed, 8 skipped, 1 xpassed, 9 warnings in 890.61s (0:14:50) ====================================================================
```

Add import control check to avoid leaking optional langchain stuff into generate/gradio.  Add test

---

README_LangChain.md
generate.py
gpt_langchain.py
gradio_runner.py
image_captions.py
make_db.py
requirements_optional_langchain.txt
tests/test_langchain_units.py
tests/test_manual_test.py
utils.py

```
FAILED tests/test_manual_test.py::test_upload_url - NotImplementedError: MANUAL TEST FOR NOW -- do and ask query of content of url
FAILED tests/test_manual_test.py::test_upload_pasted_text - NotImplementedError: MANUAL TEST FOR …
```

Add image support and show sources after upload

---

README_LangChain.md
gpt_langchain.py
gradio_runner.py
requirements_optional_langchain.gpllike.txt
requirements_optional_langchain.txt
tests/test_manual_test.py

put in URL box arxiv:1706.03762
```
FAILED tests/test_manual_test.py::test_upload_url - NotImplementedError: MANUAL TEST FOR NOW -- put in URL box arxiv:1706.03762, ensure can go to source link
FAILED …
```

ArXiv support via URL in chatbot UI

---

gradio_runner.py
gradio_themes.py

Control chats, save, export, import and otherwise manage

---

create_data.py
export_hf_checkpoint.py
finetune.py
generate.py
gradio_runner.py
loaders.py
tests/test_prompter.py

Move loaders out of finetune, which is only for training, while loader used for generation too

---

eval.py
generate.py
gradio_runner.py
utils.py

Did manual tests.  Ignore 4bit failure.
```
================================================================================================================ short test summary info ================================================================================================================
FAILED tests/test_eval.py::test_eval1[False-4] - TypeError: GPTNeoXForCausalLM.__init__() got an unexpected keyword argument 'load_in_4bit'
FAILED …
```

Refactor out run_eval out of generate.py

---

FAQ.md
README.md
README_LangChain.md
cli.py
client_test.py
eval.py
generate.py
gpt4all_llm.py
gpt_langchain.py
gradio_runner.py
tests/test_cli.py
tests/test_client_calls.py
tests/utils.py

```
(h2ollm) jon@pseudotensor:~/h2o-llm$ python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-512-6_9b --cli=True
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run
python -m bitsandbytes
and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/jon/miniconda3/envs/h2ollm did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as …
```

Add CLI mode with tests

---

generate.py
gpt_langchain.py
h2oai_pipeline.py
tests/test_eval.py
tests/test_langchain_simple.py

This now works properly (human-bot like stuff put in) and also streams properly (before was only showing up at end with sources and unstopped LLM response):
```
python generate.py --base_model=junelee/wizard-vicuna-13b --load_8bit=True --debug=True --h2ocolors=False
```
```
FAILED tests/test_manual_test.py::test_upload_multiple_file - …
```

Generalize h2oai_pipeline so works for any instruct model we have prompt_type for, so run_db_qa will stream and stop just like non-db code path

---

FAQ.md
generate.py
gpt_langchain.py
gradio_runner.py
gradio_themes.py

Ensure can use offline

---

.env_gpt4all
FAQ.md
INSTALL.md
cli.py
generate.py
gpt4all_llm.py
gpt_langchain.py
gradio_runner.py
prompter.py
requirements.txt
requirements_optional_gpt4all.txt
tests/test_cli.py
tests/test_client_calls.py

Now properly supports:
* GPT4All gptj: downloads to cache, no local file choice
* GPT4All llama (version 2 quant), downloads to cache, no local file choice
* llama-cpp-python's llama (version 3 quant)
Saw odd garbling from model had downloaded myself from  model explorer, so sticking to internal cache downloader for GPT4All.
gptj from GPT4all still has the "no output" issue, even natively.  So best to stick to llama.cpp version IMO, e.g. by downloading a version 3 quantization llama.cpp model, or build one yourself as in FAQ.md, and then doing:
```
python generate.py --base_model='llama' --langchain_mode=UserData --user_path=user_path --score_model=None
```
Tests:
```
============================================================================================================ short test …
```

Fix and test llamacpp

---

.env_gpt4all
gpt4all_llm.py
gpt_langchain.py

Improve use of ctx vs. max_new_tokens for non-HF models, and if no docs, don't insert == since no docs, just confuses model

---

.env_gpt4all
FAQ.md
README.md
create_data.py
generate.py
gpt4all_llm.py
gradio_runner.py
prompter.py
stopping.py
tests/test_cli.py
tests/test_client_calls.py
tests/utils.py

Quantized model updates, switch to recommending TheBloke 

---

README.md
cli.py
client_test.py
eval.py
generate.py
gradio_runner.py
tests/test_langchain_units.py

```
FAILED tests/test_langchain_units.py::test_md_add - AssertionError: assert 'h2oGPT is a large language model' in 'bash\ngit clone https://github.com/h2oai/h2ogpt.git\ncd h2ogpt\npip install -r requirements.txt\npython generate.py --base_model=h2oai/h2ogpt-oig-oasst1-512-6_9b --load_8bit=...
FAILED …
```

Fix nochat API

---

eval.py
generate.py

```
17 passed, 6 warnings in 396.25s (0:06:36)
```

Fix run_eval and validate parameters are all passed

---

README.md
docs/README_LangChain.md
reqs_optional/requirements_optional_faiss.txt
reqs_optional/requirements_optional_faiss_cpu.txt
setup.py

```
(h2ollm) jon@pseudotensor:~/h2ogpt$ GPU=1 python setup.py sdist bdist_wheel
running sdist
running egg_info
writing h2ogpt.egg-info/PKG-INFO
writing dependency_links to h2ogpt.egg-info/dependency_links.txt
writing requirements to h2ogpt.egg-info/requires.txt
writing top-level names to h2ogpt.egg-info/top_level.txt
reading manifest file 'h2ogpt.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'h2ogpt.egg-info/SOURCES.txt'
running check
creating h2ogpt-0.1.0
creating h2ogpt-0.1.0/h2ogpt.egg-info
creating h2ogpt-0.1.0/tests
copying files to h2ogpt-0.1.0...
copying LICENSE -> h2ogpt-0.1.0
copying README.md -> h2ogpt-0.1.0
copying setup.py -> h2ogpt-0.1.0
copying ./cli.py -> h2ogpt-0.1.0/.
copying ./client_test.py -> h2ogpt-0.1.0/.
copying ./create_data.py -> …
```

Add setup.py wheel building option

---

generate.py
gpt_langchain.py
make_db.py
reqs_optional/requirements_optional_langchain.txt
tests/test_langchain_units.py

Fixes #145
Output of running `pytest -s -v tests/test_langchain_units.py::test_qa_wiki_db_chunk_hf_weaviate`:
> ================================================================================= test session starts =================================================================================
> platform linux -- Python 3.10.11, pytest-7.3.1, pluggy-1.0.0 -- /usr/local/py-utils/venvs/pytest/bin/python
> cachedir: .pytest_cache
> rootdir: /workspaces/h2ogpt
> plugins: xdist-3.2.1, anyio-3.7.0
> collected 1 item                                                                                                                                                                      
> 
> tests/test_langchain_units.py::test_qa_wiki_db_chunk_hf_weaviate llama.cpp: loading model from …

Add weaviate support

---

docs/FAQ.md
gpt_langchain.py
gradio_runner.py
tests/test_manual_test.py

Allow update db from UI if files changed, since normally not constantly checking for new files

---

cli.py
eval.py
generate.py
gpt_langchain.py
gradio_runner.py

More control over max_max_new_tokens and memory behavior from generate args

---

cli.py
client_test.py
create_data.py
eval.py
finetune.py
generate.py
gpt_langchain.py
gradio_runner.py
h2oai_pipeline.py
prompter.py
stopping.py
tests/test_client_calls.py
tests/test_eval.py
tests/test_prompter.py

Gradio uses positional args, and so constantly breaking API when add new parameters to pass to server from client.  Already made it so returned object is string of dict.  Now made input string of dict too, i.e.:
```
from gradio_client import Client
client = Client(os.getenv('HOST', "http://localhost:7860"))
kwargs = dict(instruction_nochat='Who are you?')
res = client.predict(str(dict(kwargs)), api_name='/submit_nochat_api')
response = ast.literal_eval(res)['response']
assert 'I am h2oGPT' in response or "I'm h2oGPT" in response or 'I’m h2oGPT' in response
```
```
FAILED tests/test_manual_test.py::test_upload_one_file - …
```

Make API easier, and add prompt_dict for custom control over prompt as example of new API parameter don't need to pass

---

generate.py

Fixes following error on startup `python generate.py --base_model=distilgpt2 --load_8bit=True`
```
Traceback (most recent call last):
File "/home/sajith/src/h2ogpt/generate.py", line 1684, in <module>
fire.Fire(main)
File "/home/sajith/src/h2ogpt/venv/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
component_trace = _Fire(component, args, parsed_flag_args, context, name)
File "/home/sajith/src/h2ogpt/venv/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
component, remaining_args = _CallAndUpdateTrace(
File "/home/sajith/src/h2ogpt/venv/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
component = fn(*varargs, **kwargs)
File "/home/sajith/src/h2ogpt/generate.py", line 363, in main
get_generate_params(model_lower, chat,
File …
```

Fix `TypeError: can only concatenate str (not "list") to str` on startup

---

h2oai_pipeline.py

Fixes #249
with verbose=True in preprocess in h2oai_pipeline.py.  Works whether have massive context:
```
reducing 28144 tokens, assuming average of 3 chars/token for 6144 characters
reducing 2064 tokens, assuming average of 2 chars/token for 4096 characters
using 1395 tokens with 4096 chars
Token indices sequence length is longer than the specified maximum sequence length for this model (28144 > 2048). 
```
Or largest max_new_tokens=2048:
```
reducing 28144 tokens, assuming average of 3 chars/token for 6144 characters
reducing 2064 tokens, assuming average of 2 chars/token for 4096 characters
using 1395 tokens with 4096 chars
Reduced max_new_tokens from 2048 -> 633
```

Fixes #249

---

gradio_ui/css.py
gradio_ui/prompt_form.py

continuation of https://github.com/h2oai/h2ogpt/pull/259
- the Submit button is now primary button
- there is more spacing between the prompt input area and the action buttons below
- the proximity of prompt area with the chat area should make it more obvious they are closely linked

Submit button is now primary + more spacing between prompt area and action buttons

---

gradio_runner.py
gradio_ui/css.py
gradio_ui/prompt_form.py

continuation of https://github.com/h2oai/h2ogpt/pull/258
- input prompt - primary-color border added + change in label text
- css code moved to separate file

input prompt - primary color border added + change in label text

---

requirements.txt

to:
Still not making into code block, probably my fault.

Upgrade gradio

---

generate.py
gpt_langchain.py
h2oai_pipeline.py
stopping.py
tests/test_client_calls.py

Fixes #270
```
FAILED tests/test_manual_test.py::test_upload_unsupported_file - NotImplement...
FAILED …
```

Fixes #270

---

README.md

Describe a few dependencies that might need to be installed before installing the requirements.
`tesseract-ocr` was present twice in the `apt install`

A couple of small updates to the documentation

---

docs/INSTALL.md

Escape so it outputs `$LD_LIBRARY_PATH:/usr/local/cuda/lib64/` and not `{value of $LD_LIBRARY_PATH}:/usr/local/cuda/lib64/`

Escape so it outputs `$LD_LIBRARY_PATH:/usr/local/cuda/lib64/`

---

generate.py
loaders.py

Fixes #280 -- but response changed
```
FAILED tests/test_manual_test.py::test_upload_unsupported_file - NotImplement...
FAILED …
```

Pass actual eos id to generate, else doesn't know how to stop early if using non-standard eos id (normally=0, falcon GM was 11)

---

generate.py
gpt_langchain.py
gradio_runner.py

Fixes #291 -- make user_path if doesn't exist but passed, and move gradio temp file to user_path if passed to generate.
```
======================================================================================= 50 passed, 8 skipped, 1 xpassed, 9 warnings in 627.30s (0:10:27) ========================================================================================
(h2ollm) jon@pseudotensor:~/h2ogpt$ pytest -s -v tests/test_langchain_units.py 
```

Fixes #291 -- make user_path if doesn't exist but passed, and move gradio temp file to user_path if passed to generate.

---

cli.py
eval.py
generate.py
gpt_langchain.py
gradio_runner.py
models/modelling_RW_falcon40b.py
models/modelling_RW_falcon7b.py
tests/test_client_calls.py

Fixes #279
some terminal:
```
CUDA_VISIBLE_DEVICES=0 SCORE_MODEL=None python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v2 --langchain_mode=UserData --user_path=user_path --debug=True --concurrency_count=4
```
separate terminal:
```
STRESS=1 pytest -s -v -n 8 tests/test_client_calls.py::test_client_stress 2> stress1.log
```
instantly hit ton of:
```
File "/home/jon/.cache/huggingface/modules/transformers_modules/h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v2/9170ab20fb3de322674662f2ac4616baefe6a293/modelling_RW.py", line 93, in forward
return (q * cos) + (rotate_half(q) * sin), (k * cos) + (rotate_half(k) * sin)
RuntimeError: The size of tensor a (22) must match the size of tensor b (38) at non-singleton dimension 1
```
if use concurrency=2, then h it:
```
File …
```

Fixes #279

---

requirements.txt

Fixes https://github.com/h2oai/h2ogpt/issues/307

Use latest peft, to fix export failure.

---

gradio_runner.py

Based on the Svelte source, Gradio blocks are only hidden when visible=False. Therefore certain arguments with default values of None cause an unintended effect of displaying a block when visible=None (when the intention is to be falsey). Example: the warning message for `model_lock` showed up even when it was unspecified (None).
So as to make minimal modifications to the code, I did not add type casting where the default value is already a bool or where a `not` is present to perform the conversion.

Add explicit cast to bool for visible=kwarg[...]

---

finetune.py
generate.py
gradio_runner.py
iterators/__init__.py
iterators/iterator_pipe.py
iterators/timeout_iterator.py
tests/test_async_iterator_pipe.py
tests/test_async_timeout_iterator.py
tests/test_iterator_pipe.py
tests/test_timeout_iterator.py

Fixes #332 by using https://github.com/leangaurav/pypi_iterator, so that stream as fast as one can with short timeout=0.01 to avoid stalling any single endpoint to appear in UI.

ChatAll: stream as fast as one can with short timeout=0.01 to avoid stalling any single endpoint to appear in UI

---

generate.py
gradio_runner.py
iterators/timeout_iterator.py

Handle exceptions better when doing multi-view model lock, so don't hang (quickly check if real connection there) and don't block or fail good endpoints in chat view.  Show exceptions for bad models in chat exceptions

Handle exceptions better when doing multi-view model lock, and don't block good endpoints

---

generate.py
gpt_langchain.py
h2oai_pipeline.py

Get number of tokens after limited, although before prompt_type is applied, to reduce max_new_tokens for OpenAI, who interprets max as like a min since fail if input + max > 4096 even if don't need to generate max_new_tokens tokens, only need to generate min_new_tokens
```
Generation Failed: This model's maximum context length is 4097 tokens. However, you requested 4696 tokens (3672 in the messages, 1024 in the completion). Please reduce the length of the messages or completion.   File "/home/ubuntu/h2ogpt/iterators/timeout>
self._buffer.put(next(self._iterator))
File "/home/ubuntu/h2ogpt/gradio_runner.py", line 1149, in get_response
for output_fun in fun1():
File "/home/ubuntu/h2ogpt/generate.py", line 1622, in evaluate
response = openai.ChatCompletion.create(
File …
```

Get number of tokens after limited, although before prompt_type is applied, to reduce max_new_tokens for OpenAI

---

.gitignore
Dockerfile-runner.in
Makefile
run-gpt.sh

Once images are built, one can run like following:
```
docker run --runtime nvidia -e HF_MODEL=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 -p 8888:8888 gcr.io/vorvan/h2oai/h2ogpt-runtime:61d6aea6fff3b1190aa42eee7fa10d6c
```
- to persist cache, can add: 
```
-v `pwd`/h2ogpt_env:/h2ogpt_env
```
- to run with custom entrypoint, can modify the local run-gpt.sh then add:
```
-v `pwd`/run-gpt.sh:/run-gpt.sh
```
- to select different model, set the HF source in `HF_MODEL`

Add a docker runtime, to be used to run h2o gpt models

---

docs/README_WINDOWS.md

I am no longer using the main repo to upload wheels due to git file size limits preventing me from uploading newer versions.
I am now using this release: https://github.com/jllllll/bitsandbytes-windows-webui/releases/tag/wheels
Additionally, I have removed the part about 4bit not being supported on older GPUs as this is no longer the case.

Update Windows bitsandbytes wheel link

---

docs/README_MACOS.md

Fix #449 
Follow the instructions on doc to run llama model with MPS on Mac m1
Output:
```bash
  ~/Desktop/h2ogpt on   main !2 ❯ python generate.py --base_model=llama --cli=True                                                                                                                                                                                                                                                          ✘ INT  h2ogpt
Auto set langchain_mode=ChatLLM.  Could use MyData instead.  To allow UserData to pull files from disk, set user_path and ensure allow_upload_to_user_data=True
Using Model llama
Prep: persist_directory=db_dir_UserData does not exist, regenerating
Chose UserData but user_path is empty/None
Starting get_model: llama 
llama.cpp: loading model from …
```

Update docs for llama metal support

---

requirements.txt

Reverts h2oai/h2ogpt#485
Getting total garbage results for 4-bit after accelerate/bitsandbytes upgrade, e.g.
```
pytest -s -v tests/test_eval.py::test_eval1 -k False-4-h2oai/h2ogpt-oig-oasst1-512-6_9b
```
gives as output:
```
The normal contact',debtedodryodarodossedosschasiychinthpjunkchondrogetjaljuhjuhjuhjuhjgj &TGATwentyu(((nudharmsj2oyRurriss & 2n2u2)printhapyprassopriopoeosstelemastear-.STIStF."sseMPosintooeSRREopMPR1bepreswonderointTLbackKrisSwachjop/tlho(TLockerrbackopuntwop-termeropsinagjefinopoietfajonjoch1Swishohesirpoietintlinjurt-swithin-TGiinumiIt-termaniereintopobovetjargalisibmopreisi'bootstrap'o+utentwitalissob. (W.B.ίνiese'spojgs.sersy'BiasBheckukbojanksubb. (jukjapr. oterubmeBiancrosstermestojpruid-ubb. (tho. SSC (thill
```
it was working perfectly fine before.  It was …

Revert "Use latest bitsandbytes and accelerate."

---

papers/technical-report/compile.sh
run-gpt.sh
spaces/chatbot/repo_to_spaces.sh

Changed shell scripts for portability:
1) Changed to use /bin/sh instead of /bin/bash
Scripts all used posix-compliant commands, so /bin/sh will work and this way the scripts will run on a system that does not have bash
2) Changed backtick `` usage to "$()"
The former is largely deprecated.
3) Added quotes to variables as recommended by shellcheck utility

Minor Shell Script Changes

---

README.md

- Pushed a new h2ogpt docker-runtime image for revision [cae8cb9b46e701b4eeddf55da46297f7d55a7121](https://github.com/h2oai/h2ogpt/tree/cae8cb9b46e701b4eeddf55da46297f7d55a7121) with semver tag 0.1.0

Update readme for semver docker runtime image

---

.env_gpt4all
README.md
docs/README_GPU.md
docs/README_WHEEL.md
docs/README_offline.md
reqs_optional/requirements_optional_training.txt
requirements.txt
src/cli.py
src/eval.py
src/gen.py
src/gpt_langchain.py
src/h2oai_pipeline.py
src/image_captions.py
src/llm_exllama.py
src/loaders.py
src/prompter.py
tests/test_client_calls.py
tests/test_eval.py
tests/test_inference_servers.py
tests/test_langchain_units.py

```
python generate.py --base_model=TheBloke/Llama-2-7b-Chat-GPTQ --load_gptq="gptq_model-4bit-128g" --use_safetensors=True --prompt_type=llama2 --save_dir='7bgptq4bit` --load_exllama=True
```
Or run with RoPE scaling the LLaMa-2 7B model for 16k context:
```bash
python generate.py --base_model=TheBloke/Llama-2-7b-Chat-GPTQ --load_gptq="gptq_model-4bit-128g" --use_safetensors=True --prompt_type=llama2 --save_dir='7bgptq4bit' --load_exllama=True --revision=gptq-4bit-32g-actorder_True --rope_scaling="{'alpha_value':4}"
```
which shows how to control `alpha_value` and the `revision` for a given model on [TheBloke/Llama-2-7b-Chat-GPTQ](https://huggingface.co/TheBloke/Llama-2-7b-Chat-GPTQ).  Be careful as setting `alpha_value` higher consumes substantially more GPU memory.  Also, some models …

Support exllama

---

src/gen.py
src/gradio_runner.py

Adds additional param '--root_path' to from gradio Blocks.launch() arguments.
I've found this super simple change is a really handy feature and wanted to give it back in case others found it useful. It allows you to place the gradio interface behind a URL ingress subpath like https://domain.com/some-llm/
Thanks!

feat: expose 'root_path' from gradio

---

src/gen.py

Fix #559 
```bash
  ~/Desktop/h2ogpt on   main !2 ❯ python generate.py --base_model='llama' --prompt_type=wizard2 --score_model=None --langchain_mode='UserData'                                                                                                                                                                                ✘ INT took  1m 19s  h2ogpt
Using Model llama
Prep: persist_directory=db_dir_UserData does not exist, regenerating
Did not generate db since no sources
Starting get_model: llama 
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
llama.cpp: loading model from WizardLM-7B-uncensored.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx …
```

Isolate n_gpus base handling for CUDA from MPS

---

docs/README_LINUX.md
docs/README_offline.md
src/gen.py
src/gradio_runner.py
src/gradio_themes.py

The change enables Heap telemetry in Gradio UI to be able to improve
user experience.
The default tracking app id point to Heap project `Main` and its `Development` environment.
For any H2O.ai deployment we should use tracking app id from Heap
project `Main` and environment `Production`. @mmalohlava or from
@mtanco.
The analytics DO NOT track any prompts, only user interactions in UI
(click on buttons, links).

Document how to disable chroma telemetry

---

docs/README_MACOS.md

- the `brew install tesseract --all-languages` command in https://github.com/h2oai/h2ogpt/blob/main/docs/README_MACOS.md was incorrect - it wasn't an allowed command
- updated based on @Mathanraj-Sharma feedback

mac install readme updated - the tessaract command

---

Dockerfile

- Fixes for http://jenkins.h2o.local:8080/job/h2ogpt-docker-runtime-publish-nightly/51/ failure in conda installation

Fixes for conda installation issues

---

src/cli.py
src/eval.py
src/gen.py
src/gradio_runner.py
src/loaders.py

Goes from 5 -> 16 tokens/sec in 4-bit mode
For:
```
UserWarning: Input type into Linear4bit is torch.float16, but bnb_4bit_compute_type=torch.float32 (default). This will lead to slow inference or training speed. warnings.warn(f'Input type into Linear4bit is torch.float16, but bnb_4bit_compute_type=torch.float32 (default). This will lead to slow inference or training speed.')
```

Improve bitsandbytes usage and control in UI

---

docs/README_WINDOWS.md
finetune.py
src/client_test.py
src/create_data.py
src/enums.py
src/export_hf_checkpoint.py
src/gen.py
src/gpt_langchain.py
src/gradio_runner.py
src/h2oai_pipeline.py
src/loaders.py
src/prompter.py
src/stopping.py
tests/test_client_calls.py
tests/test_eval.py
tests/test_inference_servers.py
tests/test_langchain_simple.py
tests/test_langchain_units.py
tests/test_pipeline.py

Fixes #678 and Fixes #451 and Fixes #434

---

docs/README_WINDOWS.md

Can't run git clone without Git.

Adding install Git command to windows installation instructions

---

Dockerfile

Because of https://github.com/openai/tiktoken/blob/5d970c1100d3210b42497203d6b5c1e30cfda6cb/tiktoken/load.py#L30-L35
so set the cache to under h2oGPT cache dir, and pre-load at least the default encoding to things work in offline mode.

Improve offline caching

---

docs/README_DOCKER.md
tests/test_inference_servers.py

Make sure mounted directories exist and belong to local user, to avoid them being created under root in case dockerd uses root

More documentation updates

---

docs/README_DOCKER.md

- Rename the docker image to the gcr runtime image name for setting up vllm with docker

[Docs] Change docker image name in vllm

---

docs/README_ui.md

The original link is broken and results in `404 - page not found`

[DOCS] Fix the link to offline README

---

reqs_optional/requirements_optional_doctr.txt
src/image_doctr.py

Initial formatting of OCR is quite poor for certain things like table processing and for the LLMs to understand the structure of the text. Layout aware option makes it so the text is correctly spaced out. model can understand the structure by looking at spaces and new lines. 
```                                                                         QUARTERLY-     VOLUME,     TRANSACTIONS     &  REVENUES
Volume
1Q 2023                                                             1Q  2022                                   YoY
Sparkling    Water  (5)    Bulk (2)      Stills      Total            Sparkling   Water  BI    Bulk (2)     Stills      Total            4%
Mexico  RO                          309.5         26.4         87.6         35.2        458.8             301.9        21.3 …
```

Added the option to create OCRed documents that are layout aware

---

docs/README_MACOS.md

Was having:
```
gguf_init_from_file: invalid magic number 67676a74
error loading model: llama_model_loader: failed to load model from llama-2-7b-chat.ggmlv3.q4_0.bin
llama_load_model_from_file: failed to load model
```
- countless hours of running into issues, not understanding this magic number error
- this works, and we have metal support

doc(macos): pin `llama-cpp-python` version for support GGML

---

Dockerfile
Dockerfile-base
Makefile
docs/README_DOCKER.md
helm/h2ogpt-chart/templates/deployment.yaml
tests/test_inference_servers.py

new image compared to official runtime to date:
```
harbor.h2o.ai/h2ogpt/test-image                           12e2874700679bab7bda6d5ab61a1795   1af054b005e8   40 minutes ago      20.5GB
gcr.io/vorvan/h2oai/h2ogpt-runtime                        0.1.0                              4c7dac53226f   5 days ago          49.8GB
```

Improve docker layer caching to reduce overall image size

---

Dockerfile

Both commands below should work in case using old doc:

Add softlink to preserve compatibility with old commands from docs and readme(s)

---

src/utils.py

Fix: Utilize enable_pdf_doctr parameter in lg_to_gr function
Previously, the enable_pdf_doctr parameter was overlooked during server initialization. This commit ensures it's properly utilized within the lg_to_gr function.

enable_pdf_doctr in utils

---

gradio_utils/css.py
src/gradio_runner.py

- landing screens components re-ordered on mobile screens
- the mobile screen width break point is consistent with observed gradio breakpoint - 463px
- the `col_container` element id was brought one level up so that both sidebar and tabs live inside it

landing screens components re-ordered on mobile screens

---

gradio_utils/css.py
src/gradio_themes.py

- header styling changed on mobile screen
- the qr code is hidden on mobile screen

header styling changed on mobile screen

---

gradio_utils/css.py

- prompt area and upload button adjusted for mobile screens
- upload button is smaller on mobile screens
- default prompt textarea padding increased so that the text does not flow under the upload button

prompt area and upload button adjusted for mobile screens

---

gradio_utils/css.py
src/gradio_runner.py

- visible models:
- are no longer in the accordion
- don't have the remove-all button
- contain "Select: " before the input part

visible models don't have the remove-all button

---

Makefile

Address https://github.com/h2oai/h2ogpt/issues/826
old build:
```
root@mr-0xm4:~# ldd /h2ogpt_conda/lib/python3.10/site-packages/duckdb/duckdb.cpython-310-x86_64-linux-gnu.so
linux-vdso.so.1 (0x00007ffe587e5000)
libstdc++.so.6 => /h2ogpt_conda/lib/libstdc++.so.6 (0x00007f6daa9e4000)
libm.so.6 => /usr/lib/x86_64-linux-gnu/libm.so.6 (0x00007f6daa886000)
libgcc_s.so.1 => /h2ogpt_conda/lib/libgcc_s.so.1 (0x00007f6daa86b000)
libpthread.so.0 => /usr/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6daa848000)
libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007f6daa656000)
/lib64/ld-linux-x86-64.so.2 (0x00007f6dad7a9000)
```
vs original lib:
```
h2ogpt@3a05129bb375:~$ ldd /h2ogpt_conda/lib/python3.10/site-packages/duckdb.cpython-310-x86_64-linux-gnu.so 
linux-vdso.so.1 (0x00007fffe199d000) …
```

Build duckdb using manylinux

---

gradio_utils/css.py

- there were two unused css id definitions - they have been removed

css cleanup - two unused css id definitions removed

---

src/gradio_themes.py

dark theme
- secondary button styling improved
- label background color a bit lighter
on hover:

dark theme - secondary button styling improved, label background color a bit lighter

---

client/Makefile

- Needed for the Jenkins pipeline that pushes the nightly builds for h2ogpt client to S3

Chore: Add printing Makefile variables

---

docs/README_LINUX.md

Noticed there was an extra "wget" in the Linux docs

Remove extra wget

---

docs/README_CPU.md
docs/README_LINUX.md
docs/README_WINDOWS.md
src/gen.py

Standardized `--llamacpp_dict` on:
- ~No single~ Single quotes around keys
- Use of colon `:` (`=` leads to errors)

Standardizes `--llamacpp_dict` usage in docs

---

src/gen.py
src/gpt_langchain.py
src/gradio_runner.py
src/utils.py

Fixes #870
DuckDB chroma<0.4
SqLite chroma>=0.4
Both:
Manually tested same data source www.va.gov with about 4000 documents (pdfs, html) and 700k chunks.  duckdb database is 5GB, while new sqlite one is 9GB.

Speed-up sim search if only doing chunk_id filter.  Speed-up other various tasks if large db.

---

gradio_utils/grclient.py
src/gen.py
src/gpt_langchain.py
src/gradio_runner.py
src/utils_langchain.py
tests/test_client_calls.py

Improve timeout via max_time in UI/API

---

Makefile
requirements.txt

Add gputil to python requirements so vllm starts properly even when not running as root.

Add gputil python package

---

gradio_utils/grclient.py
src/gen.py
src/gpt_langchain.py

Tested manually for a few cases:

Catch exception if not quite in job.future._exception and raise up to gradio for adding to chat exceptions in UI or raise direct if API.

---

src/gen.py
src/gpt_langchain.py
tests/test_client_calls.py

For vllm/gradio inference only for now
Relax max_new_tokens to be per prompt
Instead of max of all prompts for summarization/extraction
To have more output for reduction, since been seeing reduction truncated despite not alot of input.

relax max_new_tokens to be per prompt

---

client/h2ogpt_client/_core.py
client/h2ogpt_client/_utils.py
docker_build_script_ubuntu.sh
docs/README_InferenceServers.md
src/cli.py
src/client_test.py
src/enums.py
src/eval.py
src/evaluate_params.py
src/gen.py
src/gpt_langchain.py
src/gradio_runner.py
src/utils.py
tests/test_client_calls.py
tests/test_eval.py

Improves queries by embedding query + answer from LLM, iteratively any number of depths.  Helps especially when user query is vague or weakly detailed.

Implement HYDE

---

client/h2ogpt_client/_core.py
client/tests/test_client.py

`client.list_models()` method returns the available models in the h2oGPT server

Add `client.list_models()` method

---

client/h2ogpt_client/_core.py
client/h2ogpt_client/_server.py
client/tests/test_client.py

Adds following APIs to the Client
- Returns the address of the connected h2oGPT server
```py
client.server.address
```
- Returns the system hash of the connected h2oGPT server
```py
client.server.hash
```

Add `client.server` API to the Client

---

helm/h2ogpt-chart/Chart.yaml
helm/h2ogpt-chart/templates/config-map.yaml
helm/h2ogpt-chart/templates/deployment.yaml

Make Helm work with external and local LLM's. When both are enabled we should not add `inference_server` to env vars instead use `MODEL_LOCK`. This PR fixes that

Make Helm work with external and local LLM's

---

client/h2ogpt_client/_completion.py
client/h2ogpt_client/_core.py
client/h2ogpt_client/_gradio_client.py
client/h2ogpt_client/_models.py
client/h2ogpt_client/_server.py
client/tests/test_client.py

```py
client = Client("https://llama.h2o.ai", h2ogpt_key=h2ogpt_key)
text_completion = client.text_completion.create()
```
```py
async def test_async():
response = await text_completion.complete(
prompt="Write a poem about the Amazon rainforest. End it with an emoji.",
enable_streaming=True,
)
async for token in response:
assert token
print(token, end="")
```
```py
def test_sync():
response = text_completion.complete_sync(
prompt="Write a poem about the Amazon rainforest. End it with an emoji.",
enable_streaming=True,
)
for token in response:
assert token
print(token, end="")
```

[Client] Add streaming support for the text completion API

---

docs/FAQ.md

This commit fixes a typo in a code sample in the FAQ

Fix Typo in FAQ

---

helm/h2ogpt-chart/Chart.yaml
helm/h2ogpt-chart/values.yaml

The default values in `overrideConfig` is causing h2oGPT to break when using external LLMs with MODEL_LOCK. This PR removes the default values and add it as a comment

[HELM] Remove default values from overrideConfig 

---

helm/h2ogpt-chart/templates/deployment.yaml
helm/h2ogpt-chart/templates/service.yaml
helm/h2ogpt-chart/values.yaml

This PR will add an option `h2ogpt.stack.enabled`, once enabled both vLLM and h2oGPT will be launched on the same pod instead of separate two.

[HELM] Add option to run vLLM and h2oGPT on same pod

---

src/gen.py
src/gradio_runner.py
tests/test_client_calls.py
tests/test_client_readme.py
tests/test_vision.py

* Undo 4b1b5e0c22671512266915521f150ac5dbe4e6cc a bit
* Don't stream back save_dict or prompt_raw or sources until end, so internally more efficient.
* Only have other methods in gen.py update save_dict or extra_dict, not overwrite, so more consistent returns in general
* Show error details in logs when evaluate_nochat fails due to vLLM server, since otherwise don't see which LLM etc from logs.

improve streaming and error logging

---

docs/FAQ.md

this PR adds the expected format for `auth.json` file, I couldn't find where this is documented, came to this format after checking [gradio_runner.py](https://github.com/h2oai/h2ogpt/blob/main/src/gradio_runner.py) and testing on the docker image

docs: faq: document auth.json file format

---

gradio_utils/grclient.py
src/cli.py
src/client_test.py
src/eval.py
src/evaluate_params.py
src/gen.py
src/gpt_langchain.py
src/gradio_runner.py
src/utils.py
tests/test_eval.py

without meta:
with all meta:
So for good models, e.g. here Nous Capybara 200k context based upon Yi 34B, meta doesn't cause issues, but of course there's less context for content.

Fixes #1270

---

docs/README_MACOS.md

```python
  ~/Desktop/h2ogpt on   main ?6 ❯ python3 generate.py --base_model=openchat/openchat-3.5-1210 --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --score_model=None --load_4bit=True --langchain_mode='UserData' --enable_tts=False --enable_stt=False --enable_transcriptions=False --max_seq_len=2048                
Using Model openchat/openchat-3.5-1210
Starting get_model: openchat/openchat-3.5-1210 
Overriding max_seq_len -> 2048
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Overriding max_seq_len -> 2048
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Overriding max_seq_len -> 2048
Starting get_model: openchat/openchat-3.5-1210 …
```

Update MacOS doc with information related to BFloat16 error

---

src/utils_langchain.py
tests/test_client_calls.py

Fixes https://github.com/h2oai/h2ogpt/issues/1298

Do map[0] instead of map_reduce if all fits into context

---

src/cli.py
src/client_test.py
src/eval.py
src/gen.py
src/gpt_langchain.py
src/gradio_runner.py
src/sagemaker.py
src/utils.py
src/utils_langchain.py
src/version.py
tests/test_client_calls.py
tests/test_langchain_units.py
tests/test_utils.py

Stream in async for summary/extract

---

helm/h2ogpt-chart/templates/deployment.yaml

add wget vllm into h2ogpt container
fixing: https://github.com/h2oai/h2ogpt/issues/1603

remove vllm-check/tgi-check init-container

---

helm/h2ogpt-chart/values.yaml

when deployed on openshift these values need to be nullified.
https://github.com/h2oai/h2ogpt/issues/1616
https://github.com/h2oai/platform-charts/pull/261

set podSecurityContext to null, so umbrella can overwrite on openshift

---

Dockerfile
Dockerfile-vllm
Makefile
helm/h2ogpt-chart/templates/deployment.yaml
helm/h2ogpt-chart/values.yaml
linux_install_wolfi.sh

Improvments for h2ogpte

---

Dockerfile

Address:
```
~:~$ docker run --rm -it --entrypoint bash gcr.io/vorvan/h2oai/h2oai-h2ogpt-vllm:0.2.0-656
bash-5.2$ python 
Python 3.10.14 (main, May  1 2024, 21:48:03) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import outlines.generate
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.10/site-packages/outlines/__init__.py", line 2, in <module>
import outlines.generate
File "/usr/lib/python3.10/site-packages/outlines/generate/__init__.py", line 1, in <module>
from .api import SequenceGenerator
File "/usr/lib/python3.10/site-packages/outlines/generate/api.py", line 5, in <module>
from outlines.fsm.fsm import FSMState
File "/usr/lib/python3.10/site-packages/outlines/fsm/fsm.py", line 9, in …
```

Set NUMBA_CACHE_DIR to a writable location by the docker user

---

helm/h2ogpt-chart/templates/deployment.yaml
helm/h2ogpt-chart/values.yaml

This PR exposes the `H2OGPT_VISIBLE_VISION_MODELS` and `H2OGPT_ROTATE_ALIGN_RESIZE_IMAGE` in Helm. Issue - https://github.com/h2oai/public-cloud-infrastructure/issues/3252

feat(helm): Add option for vision models 

---

helm/h2ogpt-chart/templates/deployment.yaml
helm/h2ogpt-chart/values.yaml

Reverts h2oai/h2ogpt#1708 because changes were superseeded by https://github.com/h2oai/h2ogpt/pull/1712

Revert "Add image models config"

---

docs/README_DOCKER.md

Update the nvidia container toolkit link according to the updated nvidia documentation. It allows the installation method to work properly on more diverse distributions, such as Ubuntu 24.04.
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

Update nvidia-container-toolkit link

---

helm/h2ogpt-chart/templates/config-map.yaml
helm/h2ogpt-chart/templates/deployment.yaml
helm/h2ogpt-chart/values.yaml
src/gen.py

Expose caCertificates in helm to it is more aligned with other h2o products.
ref: https://github.com/h2oai/h2ogpt/issues/1743#issuecomment-2243416520

Expose caCertificates in helm

---

docs/README_MACOS.md
reqs_optional/reqs_constraints.txt
reqs_optional/requirements_optional_llamacpp_gpt4all.txt
requirements.txt

These are the changes I involved to make llama 3.1 gguf work on Mac M2. 
I had to downgrade Bitsandbytes to 0.42.0 (from 0.43.1) because of a similar issue to this one : https://github.com/axolotl-ai-cloud/axolotl/issues/1436
I also had to bump some package versions :
- llama-cpp-python==0.2.85
- torch==2.3.1
Please note that I still have these warnings from llama_cpp when generating answers, but it doesn't seem to affect quality too much: 
```
h2ogpt/lib/python3.10/site-packages/llama_cpp/llama.py:1129: RuntimeWarning: Detected duplicate leading "<|begin_of_text|>" in prompt, this will likely reduce response quality, consider removing it...
``` 
I hope that it does also work on other platforms but I am not able to test

Change to make h2ogpt work on Mac M2 chip

---

Makefile
docs/FAQ.md
docs/README_DOCKER.md
docs/README_GPU.md
helm/h2ogpt-chart/values.yaml
tests/test_inference_servers.py

Port https://github.com/h2oai/h2ogpt/pull/1797 to the `main` branch.

Use a newer vllm image and update the docs and helm chart

---

Makefile

Similar change to https://github.com/h2oai/h2ogpte/pull/3318
```
~$ docker run --rm -it --entrypoint chromium gcr.io/vorvan/h2oai/h2ogpt-oss-wolfi-base:7 --version
Chromium 128.0.6613.104 
```

Update the base image

---

helm/h2ogpt-chart/templates/deployment.yaml
helm/h2ogpt-chart/templates/service.yaml

This PR exposes ports 5004 and 5000 on the Helm deployment

feat(helm): expose agent and openai port to service

---

openai_server/autogen_multi_agent_backend.py
openai_server/autogen_utils.py

- Fixes #1838
- Now returns desired outputs like: 
```
{'usage_including_cached_inference': {'total_cost': 0.040175,
'gpt-4o-2024-05-13': {'cost': 0.040175,
'prompt_tokens': 7021,
'completion_tokens': 338,
'total_tokens': 7359}},
'usage_excluding_cached_inference': {'total_cost': 0.040175,
'gpt-4o-2024-05-13': {'cost': 0.040175,
'prompt_tokens': 7021,
'completion_tokens': 338,
'total_tokens': 7359}}}
```
Reference: https://github.com/microsoft/autogen/blob/63d3297ffc66120a16e60391af538354a11e5d35/autogen/agentchat/utils.py#L29

multi_agent_type correct cost/usage calculations

---

openai_server/autogen_agents.py

- With the right message 'role', now main_group_chat_manager does better job at picking the next agent.
- (without select_speaker_prompt_template at the right place before, models get confused with the right instruction before.)
- By visual inspection, there is an obvious improvement with the right agent selection.
- A bit more promping improvements.
References: https://github.com/microsoft/autogen/blob/63d3297ffc66120a16e60391af538354a11e5d35/autogen/agentchat/groupchat.py#L108
https://github.com/microsoft/autogen/blob/63d3297ffc66120a16e60391af538354a11e5d35/autogen/agentchat/groupchat.py#L46

improved main_group_chat_manager next_agent prompting

---

openai_server/autogen_agents.py
openai_server/autogen_utils.py

- visiting final_answer_guidelines when there is no code but FINISHED_ALL_TASKS tag too.
- new guideline point for llm to start its final answer by focusing on user's initial request.

final answer improvements

---

src/utils.py

Windows often requires file paths to be formatted differently. The path used is formatted correctly for Window. Using file:/// for better cross-platform support:
```
return """<font size="%s"><a href="file:///%s" target="_blank"  rel="noopener noreferrer">%s</a></font>""" % (
```
Note the three slashes (file:///) in the link. This makes the link an absolute path which can be more reliable across different platforms.

Fix: Correct URL Scheme for File Links in HTML Output

---

openai_server/agent_prompting.py

Thanks for open-sourcing! It was a great read.
When going through the system prompt, I noticed some small typos, so I opened a PR:
- there were typos in words (packages, a lot)
- extra words (`should be include`)
- missing punctuation
- ? double spaces within bullets. I noticed too late that you have 2000 occurrences of those, so I should probably revert this change?
I didn't fix all grammar issues, just the big things that stood out as confusing. If it confuses me, it would confuse an LLM too.
Feel free to ignore/close if not helpful.

Fixing small typos in `agent_system_prompt`
