h2oai/h2ogpt

create_data.py
finetune.py
generate.py
gradio_runner.py
utils.py

Refactor gradio into separate file and isolate it from torch specific stuff

---

generate.py
gradio_runner.py
requirements.txt

See: https://gradio.app/running-background-tasks/

Clear torch cache memory every 20s

---

finetune.py
gradio_runner.py
prompter.py
tests/manual_tests.py

Working fine, random example:
chatting context used:
bit stupid:

Specify chat separator

---

generate.py
h2oai_pipeline.py
pipeline_example.py
stopping.py

```
==================================================================================== 4 passed, 1 skipped in 254.91s (0:04:14) =====================================================================================
```
and manual tests work in app and pipeline does activate stop (checked via temporary print added)

Add stopping condition to pipeline case

---

FAQ.md

This PR contains grammar / readability improvements for `FAQ.md`.

[DOCS] Grammar / readability improvements for FAQ.md

---

generate.py
gpt_langchain.py
gradio_runner.py
tests/test_langchain_units.py
utils.py

includes new zip unit test too.
```
=================================================================== 1 failed, 15 passed, 7 skipped, 1 xpassed, 9 warnings in 360.36s (0:06:00) ====================================================================
```

Add zip upload and parallel doc processing

---

gpt_langchain.py
gradio_runner.py
make_db.py
requirements.txt

Also fix chunking, so deeper inside for good parallelism.  Fixes single file upload bug.
```
=================================================================== 1 failed, 15 passed, 7 skipped, 1 xpassed, 9 warnings in 361.14s (0:06:01) ====================================================================
```

Control visibility of buttons, but still gradio issues mean can't spin/block button while processing in background

---

gpt_langchain.py
gradio_runner.py
make_db.py
requirements_optional_langchain.txt
tests/test_langchain_units.py

HF blinked out for a bit, 504 or something even in chrome, but back now.  Unlikely any issue apart from that blink
```
FAILED tests/test_client_calls.py::test_client1 - OSError: There was a specific connection error when trying to load OpenAssistant/reward-model-deberta-v3-large-v2:
=================================================================== 2 failed, 15 passed, 7 skipped, 1 xpassed, 9 warnings in 472.32s (0:07:52) ================================================================== …
```

Add URL support

---

gpt_langchain.py
gradio_runner.py
make_db.py
requirements_optional_langchain.txt
tests/test_langchain_units.py
utils.py

```
=================================================================== 1 failed, 18 passed, 7 skipped, 1 xpassed, 9 warnings in 365.91s (0:06:05) ====================================================================
```

HTML, DOCX, and better markdown support

---

README_LangChain.md
gpt_langchain.py
gradio_runner.py
requirements_optional_langchain.txt
tests/test_langchain_units.py

```
=================================================================== 1 failed, 25 passed, 8 skipped, 1 xpassed, 9 warnings in 379.96s (0:06:19) ====================================================================
```

odt, pptx, epub, UI text paste, eml support (both text/html and text/plain) and refactor so glob simpler

---

.github/workflows/snyk-scan.yml
requirements.txt

- Scan results can be found [here](https://app.snyk.io/org/h2o-gpt/projects).
- `requirements.txt` is scanned for vulnerabilities & license issues.
- Following requirements are removed from scan.
https://github.com/h2oai/h2ogpt/blob/2ccf687ea3f3f3775a501838e81c1a0066430455/requirements.txt#L42-L51
Parent Issue: https://github.com/h2oai/h2o-ops/issues/323

[DevOps] Snyk Integration

---

README.md
client_test.py
finetune.py
generate.py
gpt_langchain.py
gradio_runner.py
make_db.py
prompter.py
spaces/demo/app.py
spaces/demo/app_client_test.py
tests/test_client_calls.py
tests/test_eval.py
tests/test_eval_models.py

Improve datasource layout

---

create_data.py
eval.py
generate.py
tests/test_eval.py
tests/test_eval_models.py
utils.py

```
(h2ollm) jon@pseudotensor:~/h2ogpt$ pytest -s -v tests/test_eval.py
17 passed, 6 warnings in 402.06s (0:06:42) 
```
https://github.com/h2oai/h2ogpt/blob/8e9abe7889092e0cb5613736386a77f38994b3c6/tests/test_eval.py#L31-L39

Allow for custom eval json file

---

gpt_langchain.py
make_db.py
tests/test_langchain_units.py

FYI @hsm207 
```
FAILED tests/test_langchain_units.py::test_make_add_db[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_zip_add[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_url_add[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_html_add[weaviate] - TypeError: …
```

More weaviate tests

---

cli.py
client_test.py
eval.py
generate.py
gpt4all_llm.py
gpt_langchain.py
gradio_runner.py
h2oai_pipeline.py
tests/test_eval.py

But at least without flash attention on RTX3090Ti 24GB, 59k chars goes OOM.  E.g. when choosing no chunking (but chunking still occurs per page in some specific way), 100 chunks, then upload whisper.pdf, get OOM.
```
FAILED …
```

Chunk improve

---

docs/README_LangChain.md
gpt_langchain.py

Add documentation on how to connect to weaviate

---

docs/README_LangChain.md
generate.py
gpt_langchain.py
gradio_runner.py
tests/test_client_calls.py
tests/test_langchain_units.py

Also add cleaning after PDF parsing since often lots of extra white space that can confuse LLM.
```
FAILED …
```

Update Weaviate and FAISS a bit to be closer to Chroma in h2oGPT with limitations.  Add testing.

---

client/README.md
client/tests/test_client.py
generate.py
gpt4all_llm.py
reqs_optional/req_constraints.txt
reqs_optional/requirements_optional_faiss_cpu.txt
reqs_optional/requirements_optional_gpt4all.txt
reqs_optional/requirements_optional_langchain.txt
requirements.txt
tests/test_client_calls.py
tests/test_pipeline.py
tests/test_requirements.py
tests/test_ui.py

```
FAILED tests/test_manual_test.py::test_upload_unsupported_file - NotImplement...
FAILED …
```

Update requirements and add code to get latest versions

---

.env_gpt4all
cli.py
eval.py
generate.py
gpt_langchain.py
gradio_runner.py
tests/test_cli.py
tests/test_client_calls.py
tests/test_langchain_units.py
tests/test_ui.py

Issue: https://github.com/gradio-app/gradio/issues/4506
Temporary work around is to replace with different dollar sign so doesn't trigger latex:
``` …
```

Option to fill-up context if top_k_docs=-1

---

README.md
cli.py
create_data.py
docs/LINKS.md
enums.py
eval.py
finetune.py
generate.py
gpt_langchain.py
gradio_runner.py
gradio_ui/prompt_form.py
prompter.py
requirements.txt
tests/test_client_calls.py
tests/test_eval.py
tests/test_inference_servers.py
tests/test_langchain_units.py
tests/test_prompter.py

```
FAILED tests/test_manual_test.py::test_upload_unsupported_file - NotImplement...
FAILED …
```

Protect evaluate against bad inputs

---

gradio_runner.py

Dup with mod if existing json files have less model states, or truncate if json has more.
Fixes #324
Ignore music:
https://github.com/h2oai/h2ogpt/assets/2249614/a4db56fd-ad14-461b-94ab-99c88bdeb951

For multi-model ChatAll view, save all models together so can recover together

---

generate.py

Fixes #333 by quickly checking if can reach endpoint using requests for both gradio and HF.  Also solves slow timeout for gradio if endpoint not there.

Fixes #333 by quickly checking if can reach endpoint using requests

---

README.md
generate.py
gradio_runner.py
gradio_themes.py
gradio_ui/prompt_form.py

Wide desktop:
Narrow long desktop:
Narrow and short desktop:
iPhone:

Cleanup gradio UI a bit, ask at top so not lost at bottom

---

cli.py
eval.py
generate.py
utils.py

tried --max_max_new_tokens=2048 and looked at expert and good, and tried 1048 and looked at expert and good.

Log extra information, and fix max_max_new_tokens

---

gradio_utils/grclient.py

Also actually make robust to restarts by setting up new client, get_config not enough.

Fixes #368 by rotating session has for streaming too.

---

.env_gpt4all
README.md
gpt4all_llm.py
reqs_optional/requirements_optional_gpt4all.txt
reqs_optional/requirements_optional_langchain.txt

Fixes #382 for offloading llama to GPU using llama.cpp.
Don't upgrade gpt4all yet since messes up nctx w.r.t. langchain

Fixes #382 for offloading llama to GPU using llama.cpp.

---

docs/README_MACOS.md
requirements.txt
src/gen.py
src/utils.py

Tweaks for MAC M1

---

src/prompter.py
tests/test_prompter.py

test_prompt_with_context and test_prompt_with_no_context pass

Fix prompt answer after broken after vicuna addition

---

docs/FAQ.md

FAQ.md
- make the information about hugging face models stand out
- fix for the prompter link

FAQ.md - make the information about hugging face models stand out + fix for the prompter link

---

docs/FAQ.md

This PR fixes several typos and improves the text of the FAQ page.

[DOCS] Fix typos and improve readability (FAQ page)

---

src/gen.py

Fix attribute error for NoneType - Python 3.9

---

docs/README_InferenceServers.md
src/gen.py
src/gpt_langchain.py
src/prompter.py
src/utils.py

Add vLLM support -- Fixes #312

Add vLLM support -- Fixes #312

---

iterators/timeout_iterator.py

Fix typo in timeout_iterator.py

---

docs/README_MACOS.md

Add note to install torch 2.1 for MPS

---

gradio_utils/css.py

UI is spread to the full width

---

src/enums.py
src/prompter.py
tests/test_prompter.py

Fixes https://github.com/h2oai/h2ogpt/issues/496

add prompt template for llama2

---

Makefile

- Add semver tags for docker runtime images in vorvan as suggested here https://github.com/h2oai/h2ogpt/pull/477#issuecomment-1638221908

Add tagging docker runtime with semver

---

docs/README_GPU.md
requirements.txt
src/cli.py
src/eval.py
src/gen.py
src/loaders.py
tests/test_langchain_units.py

https://huggingface.co/TheBloke/Llama-2-70B-chat-GPTQ

LLaMa2 with AutoGPTQ and 16-bit mode with RoPE scaling

---

finetune.py
src/gen.py
src/gradio_runner.py
src/prompter.py
tests/test_prompter.py

Fixes #514 Fix llama2 prompting

---

setup.py

- Exclude `docs`, `tests`, `data`, `models/modelling_RW_falcon40b.py`, `models/modelling_RW_falcon7b.py`, `models/README-template.md`

Exclude unnecessary files & directories from wheel

---

README.md
src/gen.py
tests/test_cli.py
tests/test_client_calls.py
tests/test_inference_servers.py
tests/test_langchain_units.py

Set max_seq_len outside config, config can't always set due to protections in class

---

Makefile

- At latest tag to docker runtime & add pushing tags to vorvan

Add latest tag to docker runtime

---

docs/FAQ.md
docs/README_DOCKER.md
tests/test_inference_servers.py

Test docker of TGI + h2oGPT dockers

---

requirements.txt
src/gen.py
src/gradio_runner.py
src/utils.py
tests/test_client_calls.py

Ensure meta data in response, account for multi-yield that doesn't work if doing no streaming.  Added test.  And Fixes #649.

Ensure meta data in response and Fixes #649 and upgrade gradio

---

Dockerfile

Address https://github.com/h2oai/h2ogpt/issues/651

Fix docker permissions and allow using a non root user

---

Dockerfile
docker-compose.yml

I found it not works "out of the box" and have some mistakes in config, so I fixed some, please consider to check.

some fixes for docker run

---

README.md
docs/README_InferenceServers.md
docs/README_LINUX.md
docs/README_LangChain.md
src/gen.py
src/gpt_langchain.py
src/utils.py
tests/test_inference_servers.py

Azure OpenAI

---

gradio_utils/css.py

the copy button is placed at the bottom of each message

---

docs/README_InferenceServers.md

__Description__
- Fixes for 
- https://github.com/vllm-project/vllm/issues/754#issuecomment-1678332808
- https://github.com/vllm-project/vllm/issues/754#issuecomment-1680255688

Add pandas as a direct dependency for vLLM

---

src/gradio_runner.py
src/gradio_themes.py

The PR is in working state (dark mode works, telemetry works), but changes
intention of original code introduced in https://github.com/h2oai/h2ogpt/commit/2610e48e3c24562b3acf2a779d755eb1c7b0d8df

Fix compatibility with Gradio Blocks.

---

finetune.py
requirements.txt

Fix llama2

---

finetune.py
requirements.txt

Fixes https://github.com/h2oai/h2ogpt/issues/741
Fixes https://github.com/h2oai/h2ogpt/issues/643
Fixes https://github.com/h2oai/h2ogpt/issues/671

Bring back FSDP

---

docs/README_DOCKER.md
src/make_db.py

Address https://github.com/h2oai/h2ogpt/issues/669#issuecomment-1688565748

Fix make_db.py from docker and document in readme

---

src/gradio_runner.py

https://github.com/h2oai/h2ogpt/issues/762

Rc/#762 fixes file upload hanging on UI

---

.dockerignore
src/llm_exllama.py

The final response is no longer broken.
~~Still buggy on stream output.~~ **(fixed)**

Fixes #703 Bugfix: Broken multilanguage output

---

src/enums.py
src/gen.py
src/gpt_langchain.py
src/image_pix2struct.py
src/utils.py

added pix2struct model for better document and screenshot captioning

added pix2struct

---

docs/README_DOCKER.md
src/enums.py
src/prompter.py

https://github.com/h2oai/h2ogpt/issues/807
https://huggingface.co/spaces/tiiuae/falcon-180b-demo/blob/main/app.py#L28-L37

Add prompt type for Falcon-180B(-chat)

---

gradio_utils/css.py

related - https://github.com/h2oai/h2ogpt/issues/815

labels are brighter

---

client/h2ogpt_client/_core.py
client/h2ogpt_client/_utils.py
src/cli.py
src/client_test.py
src/enums.py
src/eval.py
src/evaluate_params.py
src/gen.py
src/gpt_langchain.py
src/gradio_runner.py
src/utils.py
tests/test_client_calls.py
tests/test_eval.py
tests/test_inference_servers.py
tests/test_perf_benchmarks.py

Noticing too much traffic on gpt.h2o.ai are through API

Keyed access

---

client/h2ogpt_client/_core.py
client/h2ogpt_client/_utils.py
docs/FAQ.md
src/cli.py
src/client_test.py
src/eval.py
src/evaluate_params.py
src/gen.py
src/gradio_runner.py
tests/test_client_calls.py
tests/test_manual_test.py
tests/test_prompter.py

Allow pre-appending chat conversation

---

src/gen.py
src/gpt_langchain.py
src/gradio_runner.py
src/make_db.py
tests/test_langchain_units.py

Fixes #873

---

src/gpt_langchain.py

Fix locking, was using common names due to os.path.basename and tasks/users were blocking each other.
Disallow locking on intrinsic names if shared type, shouldn't happen but see happening.  Fail in testing.

Fix locking

---

client/h2ogpt_client/_core.py

Tested with https://llama.h2o.ai

Move the `h2ogpt_key` param to the constructor of the `Client`

---

.github/workflows/python-package-publish.yml

- Inject version before building the version

[DevOps] Build wheel after modifying version in workflow

---

src/client_test.py
src/gen.py
src/gpt_langchain.py
src/gradio_runner.py
tests/test_client_calls.py
tests/test_inference_servers.py
tests/test_langchain_units.py
tests/test_utils.py

Fix handling of chat_conversation+system prompt using doing langchain and OpenAI (only langchain used when documents) or Azure OpenAI (requires langchain always).

Fix handling of chat_conversation+system prompt using doing langchain

---

docs/README_MACOS.md
requirements.txt

Update docs for MACOS MPS

---

README.md
docs/README_WINDOWS.md
docs/build_windows_gpu.sh
reqs_optional/requirements_optional_langchain.txt
requirements.txt
src/gpt_langchain.py
win_run_app.py
windows_installer.cfg

Update Windows Installer files for October 2023

---

.env
docker-compose-cpu.yml
docker-compose-vllm.yml
docker-compose.yml
docker_build_script_ubuntu.sh

Address: https://github.com/h2oai/h2ogpt/issues/864

Add docker compose for vllm and when running on CPU mode

---

docs/FAQ.md

This PR improves the readability of the FAQ and fixes a few typos.

[DOCS] Improve FAQ readability

---

README.md

This PR improves the readability of the README (improves clarity and adds several links)

[DOCS] Improve readability of README (second edit)

---

docs/INSTALL.md

This PR improves the readability of the `INSTALL.md` file.

[DOCS] Improve readability of INSTALL.md

---

models/gpu_mem_track.py
models/modelling_RW_falcon40b.py
models/modelling_RW_falcon7b.py

occured -> occurred
dimenstion -> dimension
stardard -> standard

Fixed typo gpu_mem_track.py modelling_RW_falcon40b.py modelling_RW_falcon7b.py

---

iterators/timeout_iterator.py

Fixed typo timeout_iterator.py

---

models/predict_aquila.py
src/enums.py
src/prompter.py
tests/test_prompter.py

Add prompt and test for https://huggingface.co/BAAI/AquilaChat2-34B-16K and related chat models, but not working with vLLM:
https://github.com/vllm-project/vllm/issues/1436

Add prompt and test for https://huggingface.co/BAAI/AquilaChat2-34B-16K and related chat models

---

client/h2ogpt_client/_core.py
client/h2ogpt_client/_utils.py
client/tests/test_client.py

Use migration-safe `/submit_nochat_api` for the ChatCompletion API

---

.env
README.md
docker_build_script_ubuntu.sh
docs/FAQ.md
docs/README_CPU.md
docs/README_DOCKER.md
docs/README_GPU.md
docs/README_LINUX.md
docs/README_LangChain.md
docs/README_MACOS.md
docs/README_WINDOWS.md
docs/README_offline.md
src/gen.py
src/gpt4all_llm.py
src/gpt_langchain.py
src/gradio_runner.py
src/h2oai_pipeline.py
src/utils.py
tests/test_cli.py
tests/test_client_calls.py
tests/test_langchain_units.py
tests/utils.py

Update get_limited_prompt and use tokenizer from llama.cpp directly

---

.gitignore
dev_installers/mac/README.md
dev_installers/mac/build_mac_installer.sh
dev_installers/mac/h2ogpt-osx-m1-cpu.spec
dev_installers/mac/mac_run_app.py
setup.py

Adding setups required for building one-click installers for MacOS. 
Fix #948

One click installer setup for MacOS

---

client/README.md

- Update the documentation for https://github.com/h2oai/h2ogpt-utils/pull/8
Parent Issue:
- https://github.com/h2oai/h2o-ops/issues/414

[Docs] Add downloading client from the GH release

---

gradio_utils/prompt_form.py
src/gen.py
src/gradio_runner.py

https://github.com/ggerganov/llama.cpp/discussions/499
Only will not segfault if doing them on inference servers.

Allow multiple llama, but llama.cpp is not thread safe, so only allowed if doing inference server for all but one.

---

dev_installers/mac/README.md
dev_installers/mac/build_mac_installer.sh
dev_installers/mac/h2ogpt-osx-m1-gpu.spec

Add configs related to MPS for one click installer

---

README.md

Adding links for Mac one-click installers to README

Add Mac one click installer to README - NOV 08, 2023

---

README.md

Based on comments https://github.com/h2oai/h2ogpt/pull/1033#issuecomment-1803926842
thanks, @gumbolastima

Commands to give permissions for Mac one-click installers

---

src/gpt_langchain.py
src/utils.py
tests/test_langchain_units.py

Parse files inside tar.gz

---

gradio_utils/css.py
src/gen.py
src/gpt_langchain.py
src/gradio_runner.py
src/utils.py

Reorganize UI a bit, and make it easier to upload url vs. text, autodetect

---

src/enums.py
src/gen.py
src/prompter.py
tests/test_prompter.py

Fixes #1082
Caution, maybe set `--max_seq_len=4096` for low-memory GPUs or use quantized version, etc
And need `--max_new_tokens=3000` or something large to get long output.

Add deepseek coder prompt

---

docs/README_ui.md

This PR contains some minor readability improvements to the UI doc.

[DOCS] Improve readability of README_ui.md

---

docs/README_CLIENT.md

This PR includes readability edits and a few typo / grammar fixes to the Client APIs README.

[DOCS] Client APIs README typo fixes and readability edit

---

docs/README_GPU.md

This PR contains various minor readability improvements to `README_GPU`.

[DOCS] Improve GPU readme

---

src/gpt_langchain.py

For Issue #1142, not a specific fix yet.  Noticed documents that failed to parse were coming up as selectable documents.  Fix that.

For Issue #1142, not a specific fix yet.  Noticed documents that failed to parse were coming up as selectable documents.  Fix that.

---

src/gpt_langchain.py

Refactored some code. Please review at your convenience.

Update gpt_langchain.py to support Youtube Shorts

---

iterators/timeout_iterator.py
src/gen.py
src/gradio_runner.py

Work-arounds for these issues:
* https://github.com/gradio-app/gradio/issues/6100
* https://github.com/gradio-app/gradio/issues/5914

Chunk streaming to help speed due to gradio UI slowness/bugs

---

docs/README_MACOS.md
docs/README_WINDOWS.md
docs/linux_install.sh
models/makevllm.sh
reqs_optional/requirements_optional_langchain.txt
src/gen.py
src/utils.py

Use openai v1 for vllm

---

README.md
docs/README_LangChain.md
docs/README_MACOS.md
docs/README_WINDOWS.md

This PR contains various minor doc improvements.

Minor doc improvements

---

README.md
docs/FINETUNE.md
docs/README_CPU.md

This PR contains various minor grammar fixes and readability improvements.

[DOCS] Minor doc fixes and improvements

---

src/enums.py
src/gpt_langchain.py
src/prompter.py

Support docsgpt https://huggingface.co/Arc53/docsgpt-7b-mistral

---

docs/FAQ.md
src/gen.py
src/gpt_langchain.py
src/loaders.py
tests/test_client_calls.py

Use transformers version of attention sinks: https://github.com/huggingface/transformers/releases/tag/v4.36.0

Use transformers version of attention sinks: https://github.com/huggingface/transformers/releases/tag/v4.36.0

---

src/gradio_runner.py

check https://github.com/h2oai/h2ogpt/issues/1207

hide action selection if only one action is enabled

---

src/gen.py
src/gradio_runner.py

based on https://github.com/gradio-app/gradio/issues/385

add ability to set custom page title and favicon

---

README.md
docs/README_InferenceServers.md
openai_server/backend.py
openai_server/log.py
openai_server/server.py
openai_server/test_conversion.py
openai_server/test_openai_server.py
src/gen.py
src/gradio_runner.py

OpenAI Proxy Server redirects to Gradio Server

---

src/eval.py
src/gen.py
tests/test_eval.py

Allow langchain for eval and add test -- Fixes #1244

Allow langchain for eval and add test -- Fixes #1244

---

docs/linux_install.sh
gradio_utils/grclient.py
tests/test_client_readme.py

-[x] Fixes #1247
-[x] Work-around https://github.com/encode/uvicorn/issues/1251  Latest anyio still doesn't fix: https://pypi.org/project/anyio/

Fixes #1247

---

helm/h2ogpt-chart/templates/deployment.yaml

This PR will make h2oGPT runtime wait until vLLM is up and running when running in stack mode
Issue - https://github.com/h2oai/public-cloud-infrastructure/issues/2561

[HELM] Add vLLM check when running as stack

---

helm/h2ogpt-chart/templates/deployment.yaml

This PR fixes an issues related to vLLM check.

Fixes to Helm Chart

---

.env
docker-compose-cpu.yml
docker-compose-vllm.yml
docker-compose.yml

address: https://github.com/h2oai/h2ogpt/issues/1265

use docker compose with a Dockerfile to force rebuild if new

---

README.md

This PR includes a few minor readability improvements to the readme.

[DOCS] readme minor readability improvements

---

helm/h2ogpt-chart/values.yaml

`imagePullSecret` and custom `tag` are actually supported in deployment.yaml, for user's reference, just exposing them in values.yaml

exposing imagePullSecret and tag in values.yaml

---

helm/h2ogpt-chart/templates/deployment.yaml

https://h2oai.slack.com/archives/C05MUTAHKU5/p1706926357058669
following the discussion here to launch 0.1.0-310 vLLM now needs shared memory on k8s '
tested working

fix-33075_adding_shared_memory

---

gradio_utils/grclient.py
reqs_optional/requirements_optional_langchain.txt
requirements.txt
src/client_test.py
src/gen.py
src/gpt_langchain.py
src/gradio_runner.py
tests/test_client_calls.py

gradio 4 client cannot talk to gradio 3 server, so this leads to breaking changes.  Any gradio server needs to be updated
https://github.com/gradio-app/gradio/issues/6353

Upgrade to gradio4 3rd attempt

---

docs/FAQ.md
docs/README_LINUX.md
docs/README_MACOS.md
docs/README_offline.md

This PR contains minor doc readability and grammar improvements.

[DOCS] Minor doc improvements

---

helm/h2ogpt-chart/templates/deployment.yaml
helm/h2ogpt-chart/values.yaml

This PR adds an option to disable pod affinity (anti affinity) on Helm deployments

[HELM] Add option to disable anti affinity 

---

openai_server/backend_utils.py
src/gen.py
src/gpt_langchain.py
src/gradio_runner.py
src/prompter.py

Fix history with images

---

src/enums.py
src/gen.py
src/gpt_langchain.py
src/image_utils.py
src/prompter.py
src/vision/utils_vision.py

Support claude-3 as vision models

---

src/enums.py
src/gen.py
src/gpt_langchain.py
src/prompter.py

Add gpt-4-vision support as vision model

---

reqs_optional/requirements_optional_langchain.txt
src/enums.py
src/gpt_langchain.py
src/gradio_runner.py
src/prompter.py

Support gemini-vision-pro as vision model

---

docs/LINKS.md

This PR fixes typos on the Links page.

[DOCS] Fix typos on Links page

---

src/gpt_langchain.py

Resolves https://github.com/h2oai/h2ogpt/pull/1460#issuecomment-2023868443.

fix: Ignore Qdrant scroll offset gpt_langchain.py

---

gradio_utils/grclient.py
openai_server/server.py
src/cli.py
src/client_test.py
src/enums.py
src/eval.py
src/evaluate_params.py
src/gen.py
src/gpt_langchain.py
src/gradio_runner.py
src/version.py
tests/test_utils.py

Isolate JSON prompts so can change language etc.

---

docs/FAQ.md

This PR contains minor grammar and readability improvements to the FAQ.

[DOCS] Minor FAQ improvements

---

gradio_utils/grclient.py
openai_server/server.py
src/cli.py
src/client_test.py
src/eval.py
src/evaluate_params.py
src/gen.py
src/gpt_langchain.py
src/gradio_runner.py
src/prompter.py
src/version.py
tests/test_eval.py

Deal with https://github.com/vllm-project/vllm/issues/4093
See also: https://github.com/outlines-dev/outlines/issues/691

guided_whitespace_pattern

---

openai_server/server_start.py
requirements.txt
src/function_server.py
src/gen.py
src/gradio_runner.py
src/version.py

https://fastapi.tiangolo.com/deployment/server-workers/
https://fastapi.tiangolo.com/deployment/server-workers/#gunicorn-with-uvicorn-workers
https://github.com/tiangolo/fastapi/issues/3955
https://stackoverflow.com/questions/66362199/what-is-the-difference-between-uvicorn-and-gunicornuvicorn
https://github.com/encode/uvicorn/issues/517

Use gunicorn so dead workers restart unlike uvicorn

---

docs/FAQ.md

This PR contains a formatting fix and minor readability edits for the FAQ.

[DOCS] FAQ formatting fix and minor readability edits

---

Makefile

Use vllm 0.5.1 https://github.com/h2oai/vllm/commits/h2ogpte/

Use vllm 0.5.1

---

Makefile

Includes fix for https://github.com/vllm-project/vllm/issues/6221

Use new vllm with flashinfer

---

helm/h2ogpt-chart/templates/config-map.yaml
helm/h2ogpt-chart/templates/deployment.yaml
helm/h2ogpt-chart/templates/service.yaml
helm/h2ogpt-chart/values.yaml

Backport https://github.com/h2oai/h2ogpt/pull/1694/files to `main`.

Port the internvl helm changes to the 'main' branch

---

docker-compose-vllm.yml
helm/h2ogpt-chart/templates/deployment.yaml
helm/h2ogpt-chart/values.yaml

Update helm to line up with this change: https://github.com/h2oai/h2ogpt/commit/2ecaf8a00cd28b257e992fbbb0f2fe40ef986bfc

Update vllm command in helm

---

helm/h2ogpt-chart/templates/deployment.yaml
helm/h2ogpt-chart/templates/service.yaml

- Fixes to service port
- Point `HF_HOME` to mount path

fix(helm): LMDeploy deployment and service

---

helm/h2ogpt-chart/templates/config-map.yaml
helm/h2ogpt-chart/templates/deployment.yaml
helm/h2ogpt-chart/templates/service.yaml
helm/h2ogpt-chart/values.yaml

Rename as per https://github.com/h2oai/h2ogpt/pull/1761#discussion_r1687453011

Rename internvl to lmdeploy

---

docs/FAQ.md
docs/README_LangChain.md
reqs_optional/requirements_optional_langchain.txt
src/gen.py
src/gpt_langchain.py
src/make_db.py
src/version.py
tests/test_client_calls.py
tests/test_langchain_units.py
tests/test_tokenizer.py
tests/utils.py

Fixes https://github.com/h2oai/h2ogpt/issues/1774

Instructor-large no longer supported for a while by sentence_transformers, need to support newer embedding models

---

Makefile

Update vllm image

---

Makefile
helm/h2ogpt-chart/values.yaml

Port https://github.com/h2oai/h2ogpt/pull/1790 to the `main` branch.

[main] Cleanup the build scripts to push directly to gcr and rename internvl to lmdeploy

---

Makefile

See https://github.com/h2oai/h2ogpte/pull/3318#issuecomment-2314337802

Update the base image to use Use Chromium 128.0.6613.84

---

Makefile

Also removed from https://github.com/h2oai/h2ogpt-utils/commit/da4589df600eedd8f8d21fa52e18ee9794563af8

Chore: Remove lmdeploy build as no longer needed, can use vllm image

---

openai_server/autogen_utils.py

only executing one code block at a time and warning the code writer agent about this.

only executing one code block

---

openai_server/autogen_2agent_backend.py
openai_server/autogen_utils.py
openai_server/server.py

autogen_use_planning_prompt as part of agent_accuracy (Have planner step only if agent_accuracy==standard or maximum)

autogen_use_planning_prompt  as part of agent_accuracy
